import json

def generate():
    # We will define a compact representation of the 100 apps and generate the full 79KB apps_data.json
    apps_list = [
        # 1. CRM
        {"id": 1, "name": "Salesforce", "category": "CRM and Sales", "desc": "Customer Relationship Management (CRM) platform for sales and support.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Can create a free Salesforce Developer Edition account to get credentials immediately.", "api": "REST & GraphQL", "api_desc": "Extremely broad APIs spanning Core, Tooling, Metadata, and User Interface.", "mcp": "Exists", "mcp_desc": "Community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.salesforce.com/docs"},
        {"id": 2, "name": "HubSpot", "category": "CRM and Sales", "desc": "Inbound marketing, sales, and service software.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Can sign up for a free Developer Account and create test developer portals.", "api": "REST", "api_desc": "Broad REST API covering Contacts, Deals, Pipelines, Webhooks, and custom objects.", "mcp": "Exists", "mcp_desc": "Official and community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.hubspot.com/docs/api/overview", "pass1_accuracy": "Incorrect", "pass2_corrected": True},
        {"id": 3, "name": "Pipedrive", "category": "CRM and Sales", "desc": "Pipeline-centric CRM for sales teams.", "auth": ["OAuth2", "API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Free Developer Sandbox account can be requested by signing up to their partner portal.", "api": "REST", "api_desc": "Comprehensive REST API covering Deals, Activities, Contacts, and Webhooks.", "mcp": "Ready", "mcp_desc": "No official MCP server but REST API is well structured.", "verdict": "Build-ready", "blocker": None, "url": "https://pipedrive.readme.io/docs"},
        {"id": 4, "name": "Attio", "category": "CRM and Sales", "desc": "Developer-first CRM and relationship database.", "auth": ["API Key", "OAuth2"], "status": "Self-serve", "path": "Anyone can register for a free account and generate API keys in developer settings.", "api": "REST", "api_desc": "Modern REST API covering Workspace, Lists, Records, and Attributes.", "mcp": "Ready", "mcp_desc": "Excellent OpenAPI spec allows generating an MCP server instantly.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.attio.com/"},
        {"id": 5, "name": "Twenty", "category": "CRM and Sales", "desc": "Open-source CRM built as a modern alternative to Salesforce.", "auth": ["API Key", "OAuth2"], "status": "Self-serve", "path": "Self-host or sign up to Twenty Cloud for free and generate developer credentials.", "api": "REST & GraphQL", "api_desc": "Fully documented REST and GraphQL endpoints reflecting the database schema.", "mcp": "Ready", "mcp_desc": "Open-source structure is highly modular and ready for an MCP server.", "verdict": "Build-ready", "blocker": None, "url": "https://twenty.com/developers"},
        {"id": 6, "name": "Podio", "category": "CRM and Sales", "desc": "Customizable work management software.", "auth": ["OAuth2", "API Key"], "status": "Self-serve", "path": "Free plan allows generating API keys and Client IDs directly from developer settings.", "api": "REST", "api_desc": "Extensive API covering workspaces, items, files, and users.", "mcp": "Ready", "mcp_desc": "Clean REST endpoints but older infrastructure.", "verdict": "Build-ready", "blocker": None, "url": "https://api-docs.podio.com/"},
        {"id": 7, "name": "Zoho CRM", "category": "CRM and Sales", "desc": "Enterprise CRM by Zoho with multi-channel support.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Free developer accounts can be registered through Zoho Developer Console.", "api": "REST", "api_desc": "Very broad API covering Modules, Blueprints, Wizards, and Custom Functions.", "mcp": "Ready", "mcp_desc": "REST API exists, OAuth2 requirements add configuration complexity.", "verdict": "Build-ready", "blocker": None, "url": "https://www.zoho.com/crm/developer/"},
        {"id": 8, "name": "Close", "category": "CRM and Sales", "desc": "Inside sales CRM with built-in calling and emailing features.", "auth": ["API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for a 14-day free trial and obtain API key under settings.", "api": "REST", "api_desc": "Clean REST API mapping Leads, Contacts, Activities, and Custom Fields.", "mcp": "Ready", "mcp_desc": "Very agent-friendly REST API due to API key authentication.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.close.com/"},
        {"id": 9, "name": "Copper", "category": "CRM and Sales", "desc": "CRM built specifically for Google Workspace users.", "auth": ["API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Start a free trial and create API keys from Settings > Integrations.", "api": "REST", "api_desc": "Basic REST API matching standard CRM record types.", "mcp": "Ready", "mcp_desc": "API Key auth allows straightforward tool mapping.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.copper.com/"},
        {"id": 10, "name": "DealCloud", "category": "CRM and Sales", "desc": "Specialized CRM for financial firms, private equity, and investment banking.", "auth": ["OAuth2"], "status": "Gated (Enterprise/Contact Sales)", "path": "No self-serve sign up. Credentials are only provided to existing enterprise customers.", "api": "REST", "api_desc": "REST API for querying private database models and reporting.", "mcp": "Blocker", "mcp_desc": "Blocked by strict enterprise gates.", "verdict": "Gated-ready", "blocker": "Requires paid enterprise subscription.", "url": "https://api.docs.dealcloud.com/"},

        # 2. Support
        {"id": 11, "name": "Zendesk", "category": "Support and Helpdesk", "desc": "Cloud-based customer support ticket management system.", "auth": ["OAuth2", "API Token", "Basic"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for Zendesk Developer program or a free trial to create credentials.", "api": "REST", "api_desc": "Extremely broad API with endpoints for Tickets, Users, Orgs, and Help Center.", "mcp": "Exists", "mcp_desc": "Community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.zendesk.com/api/reference/"},
        {"id": 12, "name": "Intercom", "category": "Support and Helpdesk", "desc": "Customer messaging platform and helpdesk.", "auth": ["OAuth2", "Token"], "status": "Self-serve (Trial/Sandbox)", "path": "Can create a free Developer Workspace for sandbox testing.", "api": "REST", "api_desc": "Broad REST API for Contacts, Conversations, Messages, and Help Center articles.", "mcp": "Ready", "mcp_desc": "API has excellent webhooks and schema specs.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.intercom.com/docs/"},
        {"id": 13, "name": "Freshdesk", "category": "Support and Helpdesk", "desc": "Helpdesk software for managing customer tickets.", "auth": ["API Key", "Basic"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for a free trial and access the API key under profile settings.", "api": "REST", "api_desc": "REST API covering Tickets, Agents, Customers, and Solutions.", "mcp": "Ready", "mcp_desc": "Clean API endpoints with static token auth.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.freshdesk.com/api/"},
        {"id": 14, "name": "Front", "category": "Support and Helpdesk", "desc": "Customer communication platform compiling emails and chats into shared inboxes.", "auth": ["API Key", "OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Register for a free developer sandbox account via their developer program.", "api": "REST", "api_desc": "JSON REST API for managing inboxes, messages, teams, and channels.", "mcp": "Ready", "mcp_desc": "Clean schema definitions with static token option.", "verdict": "Build-ready", "blocker": None, "url": "https://dev.frontapp.com/"},
        {"id": 15, "name": "Pylon", "category": "Support and Helpdesk", "desc": "Customer support platform designed for Slack/Teams-first customer operations.", "auth": ["API Key"], "status": "Gated (Enterprise/Contact Sales)", "path": "Must book a demo/talk to sales to get access. No public signup/trial.", "api": "REST", "api_desc": "REST API for linking Slack conversations to support queues.", "mcp": "Blocker", "mcp_desc": "Lack of developer sandbox makes sandbox testing impossible.", "verdict": "Gated-ready", "blocker": "No public trial or free developer sandbox available.", "url": "https://docs.usepylon.com/"},
        {"id": 16, "name": "LiveAgent", "category": "Support and Helpdesk", "desc": "Omnichannel helpdesk and live chat software.", "auth": ["API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Register for a free trial to obtain API key in settings.", "api": "REST", "api_desc": "REST API for agents, tickets, chats, and calls.", "mcp": "Ready", "mcp_desc": "Simple token auth leads to quick setup.", "verdict": "Build-ready", "blocker": None, "url": "https://api.liveagent.com/"},
        {"id": 17, "name": "Plain", "category": "Support and Helpdesk", "desc": "Developer-first customer support platform with linear style interfaces.", "auth": ["API Key"], "status": "Self-serve", "path": "Free tier allows generating API keys in settings.", "api": "GraphQL", "api_desc": "GraphQL API for managing support threads, customers, and events.", "mcp": "Ready", "mcp_desc": "GraphQL schema simplifies querying.", "verdict": "Build-ready", "blocker": None, "url": "https://www.plain.com/docs/"},
        {"id": 18, "name": "Help Scout", "category": "Support and Helpdesk", "desc": "Shared inbox and customer support tool for teams.", "auth": ["OAuth2", "API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for a free trial to generate OAuth credentials/tokens.", "api": "REST", "api_desc": "REST API V2 covering Mailboxes, Conversations, Customers, and Docs.", "mcp": "Ready", "mcp_desc": "Well-documented and structured REST endpoints.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.helpscout.com/"},
        {"id": 19, "name": "Gorgias", "category": "Support and Helpdesk", "desc": "Ecommerce-focused customer service helpdesk.", "auth": ["API Key", "Basic"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for a free trial, then get API key under settings.", "api": "REST", "api_desc": "REST API designed to sync with Shopify/Magento and manage tickets.", "mcp": "Ready", "mcp_desc": "Very straightforward endpoints.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.gorgias.com/"},
        {"id": 20, "name": "Gladly", "category": "Support and Helpdesk", "desc": "People-centered customer service platform.", "auth": ["API Token", "Basic"], "status": "Gated (Enterprise/Contact Sales)", "path": "Contact sales to purchase a license. No free developer signup.", "api": "REST", "api_desc": "REST APIs for customer profiles, conversations, and custom channels.", "mcp": "Blocker", "mcp_desc": "Requires enterprise authorization.", "verdict": "Gated-ready", "blocker": "No developer program or self-serve trials exist.", "url": "https://connect.gladly.com/api/"},

        # 3. Communications
        {"id": 21, "name": "Slack", "category": "Communications and Messaging", "desc": "Team collaboration chat platform.", "auth": ["OAuth2"], "status": "Self-serve", "path": "Can create a free workspace and build a Slack app to get bot tokens immediately.", "api": "REST", "api_desc": "Extremely broad API covering chat, files, channels, webhooks, and users.", "mcp": "Exists", "mcp_desc": "Official and community Slack MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://api.slack.com/"},
        {"id": 22, "name": "Twilio", "category": "Communications and Messaging", "desc": "Cloud communications platform for SMS, Voice, and Video.", "auth": ["Basic"], "status": "Self-serve", "path": "Sign up for a free developer trial account to get Account SID and Auth Token.", "api": "REST", "api_desc": "Extremely broad REST API with SDK support across major languages.", "mcp": "Ready", "mcp_desc": "API structure and Basic auth make it an ideal target.", "verdict": "Build-ready", "blocker": None, "url": "https://www.twilio.com/docs"},
        {"id": 23, "name": "Zoho Cliq", "category": "Communications and Messaging", "desc": "Business chat and team collaboration app by Zoho.", "auth": ["OAuth2"], "status": "Self-serve", "path": "Register on Zoho Developer Console to build extensions and get keys.", "api": "REST", "api_desc": "REST API covering chats, bots, channels, and widgets.", "mcp": "Ready", "mcp_desc": "Follows standard Zoho OAuth flow.", "verdict": "Build-ready", "blocker": None, "url": "https://www.zoho.com/cliq/help/restapi/v2/"},
        {"id": 24, "name": "Lark (Larksuite)", "category": "Communications and Messaging", "desc": "All-in-one collaborative suit containing chats, drive, and calendars.", "auth": ["Token"], "status": "Self-serve", "path": "Create a free Lark account and visit the Open Platform to create an app.", "api": "REST", "api_desc": "Extensive API covering spreadsheet, messaging, and admin tools.", "mcp": "Ready", "mcp_desc": "Lark has a very modern API interface.", "verdict": "Build-ready", "blocker": None, "url": "https://open.larksuite.com/"},
        {"id": 25, "name": "Pumble", "category": "Communications and Messaging", "desc": "Team chat app with similar interfaces to Slack.", "auth": ["API Key"], "status": "Self-serve", "path": "Sign up for a free workspace and generate tokens in the settings dashboard.", "api": "REST", "api_desc": "Simple REST API covering channels and messages.", "mcp": "Ready", "mcp_desc": "API has lower complexity.", "verdict": "Build-ready", "blocker": None, "url": "https://pumble.com/help/"},
        {"id": 26, "name": "Discord", "category": "Communications and Messaging", "desc": "Voice, video, and text communication platform for communities.", "auth": ["OAuth2", "Token"], "status": "Self-serve", "path": "Register an application on Discord Developer Portal to generate Bot tokens.", "api": "REST", "api_desc": "Broad REST API + WebSockets for gateway connections.", "mcp": "Exists", "mcp_desc": "Discord community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://discord.com/developers/docs/intro"},
        {"id": 27, "name": "Telegram", "category": "Communications and Messaging", "desc": "Cloud-based mobile and desktop messaging app.", "auth": ["Token"], "status": "Self-serve", "path": "Create a bot using BotFather directly in the Telegram app to get tokens instantly.", "api": "REST", "api_desc": "Simple HTTP REST Bot API alongside MTProto protocol.", "mcp": "Exists", "mcp_desc": "Telegram bot MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://core.telegram.org/bots/api"},
        {"id": 28, "name": "WhatsApp Business", "category": "Communications and Messaging", "desc": "API for large businesses to communicate with customers on WhatsApp.", "auth": ["Token"], "status": "Self-serve", "path": "Sign up on Meta for Developers portal, register a test number and get free tokens.", "api": "REST", "api_desc": "Graph API REST endpoints for sending templates, media, and text.", "mcp": "Ready", "mcp_desc": "Standardized Meta Graph API endpoints.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.facebook.com/docs/whatsapp", "pass1_accuracy": "Incorrect", "pass2_corrected": True},
        {"id": 29, "name": "Aircall", "category": "Communications and Messaging", "desc": "Cloud-based call center software integrating with CRMs.", "auth": ["API Key", "Basic"], "status": "Self-serve (Trial/Sandbox)", "path": "Start a free trial, then generate API keys from the admin dashboard.", "api": "REST", "api_desc": "REST API covering calls, users, contacts, and numbers.", "mcp": "Ready", "mcp_desc": "Straightforward REST mapping.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.aircall.io/"},
        {"id": 30, "name": "Vonage", "category": "Communications and Messaging", "desc": "Global cloud communications platform formerly known as Nexmo.", "auth": ["API Key", "JWT"], "status": "Self-serve", "path": "Register on Vonage Developer API portal to get free API keys and secret.", "api": "REST", "api_desc": "Broad APIs spanning SMS, Voice, Verify (2FA), and Video.", "mcp": "Ready", "mcp_desc": "Excellent OpenAPI specs are available.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.vonage.com/"},

        # 4. Marketing
        {"id": 31, "name": "Google Ads", "category": "Marketing, Ads, Email and Social", "desc": "Online advertising platform by Google.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Free Developer Token can be generated in Google Ads Manager, but requires approval.", "api": "REST", "api_desc": "Very broad API for managing campaigns, budgets, and keyword planning.", "mcp": "Ready", "mcp_desc": "Requires Developer Token header in addition to OAuth2.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.google.com/google-ads/api/docs/start"},
        {"id": 32, "name": "Meta Ads", "category": "Marketing, Ads, Email and Social", "desc": "Advertising platform across Facebook, Instagram, and Messenger.", "auth": ["OAuth2"], "status": "Self-serve", "path": "Create a Meta Developer app and use the Graph API Explorer.", "api": "REST", "api_desc": "Graph API REST endpoint representing ad campaigns, creatives, and insights.", "mcp": "Ready", "mcp_desc": "Broad API but Meta Graph structure is complex.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.facebook.com/docs/marketing-apis/"},
        {"id": 33, "name": "LinkedIn Ads", "category": "Marketing, Ads, Email and Social", "desc": "Professional marketing and advertising solutions on LinkedIn.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Request access to Marketing Developer Platform via LinkedIn Developer Portal.", "api": "REST", "api_desc": "REST APIs representing Ad Accounts, Campaigns, and Reporting.", "mcp": "Ready", "mcp_desc": "LinkedIn API portal requires brief application review.", "verdict": "Build-ready", "blocker": None, "url": "https://learn.microsoft.com/en-us/linkedin/marketing/"},
        {"id": 34, "name": "GoHighLevel", "category": "Marketing, Ads, Email and Social", "desc": "All-in-one marketing and business automation platform for agencies.", "auth": ["OAuth2", "API Key"], "status": "Gated (Paid)", "path": "Requires a paid GoHighLevel account to generate API keys in Settings.", "api": "REST", "api_desc": "REST API V2 mapping Contacts, Calendars, Pipelines, and SMS templates.", "mcp": "Blocker", "mcp_desc": "No developer trial; must pay $97+/mo to access the API.", "verdict": "Gated-ready", "blocker": "Requires a paid plan to get developer credentials.", "url": "https://highlevel.stoplight.io/"},
        {"id": 35, "name": "Mailchimp", "category": "Marketing, Ads, Email and Social", "desc": "Marketing automation and email marketing service.", "auth": ["OAuth2", "API Key"], "status": "Self-serve", "path": "Free tier allows generating API keys in user account dashboard.", "api": "REST", "api_desc": "REST API covering lists, campaigns, reports, and members.", "mcp": "Ready", "mcp_desc": "Very agent-friendly due to clear structure.", "verdict": "Build-ready", "blocker": None, "url": "https://mailchimp.com/developer/"},
        {"id": 36, "name": "Klaviyo", "category": "Marketing, Ads, Email and Social", "desc": "Marketing automation platform for ecommerce stores.", "auth": ["API Key", "OAuth2"], "status": "Self-serve", "path": "Sign up for a free developer sandbox and generate API keys.", "api": "REST", "api_desc": "REST API covering profiles, lists, metrics, and templates.", "mcp": "Ready", "mcp_desc": "Modern OpenAPI specification available.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.klaviyo.com/"},
        {"id": 37, "name": "systeme.io", "category": "Marketing, Ads, Email and Social", "desc": "All-in-one online platform for marketing, sales funnels, and courses.", "auth": ["API Key"], "status": "Self-serve", "path": "Create a free account and generate API keys under profile settings.", "api": "REST", "api_desc": "Simple REST API mapping leads, contacts, and purchases.", "mcp": "Ready", "mcp_desc": "Basic API key mapping.", "verdict": "Build-ready", "blocker": None, "url": "https://systeme.io/help/api"},
        {"id": 38, "name": "Pinterest", "category": "Marketing, Ads, Email and Social", "desc": "Social curation and image sharing network.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Create a developer app on Pinterest Developer portal to get trial keys.", "api": "REST", "api_desc": "REST API for Boards, Pins, Analytics, and Audiences.", "mcp": "Ready", "mcp_desc": "Standard OAuth2 flow.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.pinterest.com/"},
        {"id": 39, "name": "Threads (Meta)", "category": "Marketing, Ads, Email and Social", "desc": "Text-based social network by Meta.", "auth": ["OAuth2"], "status": "Self-serve", "path": "Configure the Threads API product inside a Meta Developer App.", "api": "REST", "api_desc": "REST endpoints representing posts, media, and user metrics.", "mcp": "Ready", "mcp_desc": "Recently released public API.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.facebook.com/docs/threads/"},
        {"id": 40, "name": "SendGrid", "category": "Marketing, Ads, Email and Social", "desc": "Cloud-based email delivery and transactional email service.", "auth": ["API Key"], "status": "Self-serve", "path": "Register for a free account and generate an API key instantly.", "api": "REST", "api_desc": "JSON REST API covering mail send, lists, statistics, and subaccounts.", "mcp": "Ready", "mcp_desc": "Excellent OpenAPI specification.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.sendgrid.com/api-reference"},

        # 5. Ecommerce
        {"id": 41, "name": "Shopify", "category": "Ecommerce", "desc": "Leading ecommerce platform for online stores.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Create a free Shopify Partner account to set up developer sandbox stores.", "api": "REST & GraphQL", "api_desc": "Very broad APIs. GraphQL is the primary interface for admin.", "mcp": "Exists", "mcp_desc": "Community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://shopify.dev/docs/api", "pass1_accuracy": "Incorrect", "pass2_corrected": True},
        {"id": 42, "name": "WooCommerce", "category": "Ecommerce", "desc": "Open-source customizable ecommerce plugin built for WordPress.", "auth": ["Basic"], "status": "Self-serve", "path": "Free WordPress plugin. Generate Consumer Key/Secret in WordPress dashboard.", "api": "REST", "api_desc": "Broad REST API covering products, orders, coupons, and settings.", "mcp": "Ready", "mcp_desc": "Self-hosted nature means URLs vary.", "verdict": "Build-ready", "blocker": None, "url": "https://woocommerce.github.io/code-reference/"},
        {"id": 43, "name": "BigCommerce", "category": "Ecommerce", "desc": "SaaS ecommerce platform for merchants.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Can create a free 15-day trial store or developer sandbox account.", "api": "REST & GraphQL", "api_desc": "Broad REST Storefront/Management API.", "mcp": "Ready", "mcp_desc": "Has standard API scopes.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.bigcommerce.com/"},
        {"id": 44, "name": "Salesforce Commerce Cloud", "category": "Ecommerce", "desc": "Enterprise cloud commerce platform for brands.", "auth": ["OAuth2"], "status": "Gated (Enterprise/Contact Sales)", "path": "Requires partner credentials or existing enterprise contract. No public signup.", "api": "REST", "api_desc": "OCAPI and SCAPI REST endpoints.", "mcp": "Blocker", "mcp_desc": "Blocked by enterprise contract requirements.", "verdict": "Gated-ready", "blocker": "Requires enterprise-tier license.", "url": "https://developer.salesforce.com/docs/commerce"},
        {"id": 45, "name": "Magento (Adobe Commerce)", "category": "Ecommerce", "desc": "Open-source and enterprise ecommerce platform by Adobe.", "auth": ["Token", "OAuth1"], "status": "Self-serve", "path": "Free Open Source version can be downloaded and run locally.", "api": "REST & GraphQL", "api_desc": "Large REST and GraphQL surface area.", "mcp": "Ready", "mcp_desc": "Self-hosted setups need endpoint configuration.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.adobe.com/commerce/"},
        {"id": 46, "name": "Squarespace", "category": "Ecommerce", "desc": "Website builder with ecommerce capabilities.", "auth": ["API Key"], "status": "Gated (Paid)", "path": "Requires a paid Website Business or Commerce plan to generate API keys.", "api": "REST", "api_desc": "Basic REST API for Inventory, Orders, and Transactions.", "mcp": "Blocker", "mcp_desc": "Blocked by payment wall to access developer panel.", "verdict": "Gated-ready", "blocker": "Requires a paid subscription (Business/Commerce plan).", "url": "https://developers.squarespace.com/"},
        {"id": 47, "name": "Ecwid", "category": "Ecommerce", "desc": "SaaS shopping cart plugin for existing websites.", "auth": ["OAuth2"], "status": "Self-serve", "path": "Register on Ecwid Developers console for a free Developer Account.", "api": "REST", "api_desc": "REST API covering orders, products, and customers.", "mcp": "Ready", "mcp_desc": "Clean endpoints with standard OAuth flow.", "verdict": "Build-ready", "blocker": None, "url": "https://api-docs.ecwid.com/"},
        {"id": 48, "name": "Gumroad", "category": "Ecommerce", "desc": "E-commerce platform for creators to sell digital products directly.", "auth": ["OAuth2", "API Key"], "status": "Self-serve", "path": "Free account allows creating Personal Access Tokens in settings.", "api": "REST", "api_desc": "REST API for products, subscribers, and sales.", "mcp": "Ready", "mcp_desc": "Simple token auth leads to quick setup.", "verdict": "Build-ready", "blocker": None, "url": "https://gumroad.com/api"},
        {"id": 49, "name": "Amazon Selling Partner", "category": "Ecommerce", "desc": "REST API for Amazon sellers to manage inventories and shipments.", "auth": ["OAuth2"], "status": "Gated (Paid)", "path": "Requires a paid Amazon Seller Professional Account ($39.99/mo) and developer registration.", "api": "REST", "api_desc": "Broad API with strict security standards (AWS IAM/LWA).", "mcp": "Blocker", "mcp_desc": "Requires active Amazon Seller subscription.", "verdict": "Gated-ready", "blocker": "Requires a paid Amazon Seller Professional subscription.", "url": "https://developer-docs.amazon.com/sp-api"},
        {"id": 50, "name": "fanbasis", "category": "Ecommerce", "desc": "Monetization and digital marketplace platform for creators.", "auth": ["API Key"], "status": "Gated (Enterprise/Contact Sales)", "path": "Private beta. No public documentation or API access.", "api": "None", "api_desc": "No public API surface exists today.", "mcp": "Blocker", "mcp_desc": "No API is available.", "verdict": "Blocker", "blocker": "No public developer API available.", "url": "https://fanbasis.com/"},

        # 6. Data & SEO
        {"id": 51, "name": "DataForSEO", "category": "Data, SEO and Scraping", "desc": "SEO and search engine scraping data APIs.", "auth": ["Basic"], "status": "Self-serve", "path": "Register for free and receive $1 trial credit; uses Basic Auth (Login/Password).", "api": "REST", "api_desc": "Very broad API covering SERP, Keywords, Domain data, and SEO checks.", "mcp": "Ready", "mcp_desc": "API has excellent structural documentation.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.dataforseo.com/"},
        {"id": 52, "name": "SE Ranking", "category": "Data, SEO and Scraping", "desc": "All-in-one SEO platform.", "auth": ["API Key"], "status": "Gated (Paid)", "path": "Requires a paid subscription plan to request API access.", "api": "REST", "api_desc": "REST API covering ranking, audit, and competitor data.", "mcp": "Blocker", "mcp_desc": "Requires paid plan for API credentials.", "verdict": "Gated-ready", "blocker": "Requires a paid plan to activate API tokens.", "url": "https://seranking.com/api.html"},
        {"id": 53, "name": "Ahrefs", "category": "Data, SEO and Scraping", "desc": "Industry-leading SEO toolset for backlinks.", "auth": ["API Key", "OAuth2"], "status": "Gated (Paid)", "path": "Requires a paid Ahrefs Enterprise or Custom plan to access API.", "api": "REST", "api_desc": "Broad API with detailed indices of web data.", "mcp": "Blocker", "mcp_desc": "Blocked by high paywall.", "verdict": "Gated-ready", "blocker": "Requires Enterprise/Custom plans.", "url": "https://ahrefs.com/api"},
        {"id": 54, "name": "MrScraper", "category": "Data, SEO and Scraping", "desc": "Visual web scraper and automated scraping tool.", "auth": ["API Key"], "status": "Self-serve", "path": "Register for a free account to generate API keys in profile.", "api": "REST", "api_desc": "REST API to trigger scrapers and retrieve results.", "mcp": "Ready", "mcp_desc": "Simple token auth.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.mrscraper.com/"},
        {"id": 55, "name": "Apify", "category": "Data, SEO and Scraping", "desc": "Cloud platform for web scraping and RPA.", "auth": ["API Key"], "status": "Self-serve", "path": "Sign up for free and get API tokens in console dashboard.", "api": "REST", "api_desc": "Very broad API to execute Actors and get datasets.", "mcp": "Exists", "mcp_desc": "Community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.apify.com/api/v2"},
        {"id": 56, "name": "Firecrawl", "category": "Data, SEO and Scraping", "desc": "LLM-ready scraping tool that converts web pages into markdown.", "auth": ["API Key"], "status": "Self-serve", "path": "Sign up for free to get an API key and 500 free scrape credits.", "api": "REST", "api_desc": "Simple REST API for crawl and scrape.", "mcp": "Exists", "mcp_desc": "Official and community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.firecrawl.dev/"},
        {"id": 57, "name": "Bright Data", "category": "Data, SEO and Scraping", "desc": "Web scraping and proxy network platform.", "auth": ["API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up with credit card verification for free trial credits.", "api": "REST", "api_desc": "REST API for proxies and Scraping Browsers.", "mcp": "Ready", "mcp_desc": "Developer-centric API design.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.brightdata.com/"},
        {"id": 58, "name": "Sherlock", "category": "Data, SEO and Scraping", "desc": "Open-source OSINT tool to find usernames across social networks.", "auth": ["None"], "status": "Self-serve", "path": "Open source CLI tool, no credentials or signup required.", "api": "CLI", "api_desc": "Command-line interface with no hosted API endpoints.", "mcp": "Ready", "mcp_desc": "Can be packaged as local CLI-based MCP server.", "verdict": "Build-ready", "blocker": None, "url": "https://github.com/sherlock-project/sherlock"},
        {"id": 59, "name": "Waterfall.io", "category": "Data, SEO and Scraping", "desc": "Mobile communications and marketing messaging provider.", "auth": ["API Key"], "status": "Gated (Enterprise/Contact Sales)", "path": "Must contact sales. Closed enterprise API, no self-serve trials.", "api": "REST", "api_desc": "SMS and push campaign APIs.", "mcp": "Blocker", "mcp_desc": "Private documentation.", "verdict": "Blocker", "blocker": "Private developer program with sales gate.", "url": "https://waterfall.io/"},
        {"id": 60, "name": "Clay", "category": "Data, SEO and Scraping", "desc": "Data enrichment spreadsheet tool.", "auth": ["API Key"], "status": "Self-serve", "path": "Generate API keys in account settings; small free limit.", "api": "REST", "api_desc": "Simple REST API to trigger workspace runs.", "mcp": "Ready", "mcp_desc": "Good spec, token auth.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.clay.com/"},

        # 7. Developer
        {"id": 61, "name": "GitHub", "category": "Developer, Infra and Data platforms", "desc": "Git repository hosting and developer collaboration platform.", "auth": ["OAuth2", "API Key"], "status": "Self-serve", "path": "Sign up for free and generate Personal Access Tokens or register GitHub Apps.", "api": "REST & GraphQL", "api_desc": "Extremely broad APIs mapping all features.", "mcp": "Exists", "mcp_desc": "Official and community GitHub MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.github.com/rest"},
        {"id": 62, "name": "Vercel", "category": "Developer, Infra and Data platforms", "desc": "Hosting platform for frontend frameworks.", "auth": ["API Key"], "status": "Self-serve", "path": "Create a free account and generate Personal Access Tokens in account settings.", "api": "REST", "api_desc": "REST API covering deployments, domains, and projects.", "mcp": "Exists", "mcp_desc": "Community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://vercel.com/docs/rest-api"},
        {"id": 63, "name": "Netlify", "category": "Developer, Infra and Data platforms", "desc": "Cloud hosting and serverless platform.", "auth": ["OAuth2", "API Key"], "status": "Self-serve", "path": "Generate Personal Access Tokens under User Settings.", "api": "REST", "api_desc": "REST API for deployments, forms, and sites.", "mcp": "Ready", "mcp_desc": "Well-documented OpenAPI specification.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.netlify.com/api/get-started/"},
        {"id": 64, "name": "Cloudflare", "category": "Developer, Infra and Data platforms", "desc": "Web infrastructure and security services.", "auth": ["API Key", "Token"], "status": "Self-serve", "path": "Create a free account and generate API Tokens.", "api": "REST", "api_desc": "Very broad API covering zones, workers, and DNS.", "mcp": "Exists", "mcp_desc": "Community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.cloudflare.com/api/"},
        {"id": 65, "name": "Supabase", "category": "Developer, Infra and Data platforms", "desc": "Open-source backend-as-a-service.", "auth": ["API Key", "Token"], "status": "Self-serve", "path": "Create a free project and find Anon/Service Role API keys.", "api": "REST & GraphQL", "api_desc": "PostgREST and GraphQL interfaces.", "mcp": "Ready", "mcp_desc": "Clean structures, excellent database mapping.", "verdict": "Build-ready", "blocker": None, "url": "https://supabase.com/docs/guides/api"},
        {"id": 66, "name": "Neo4j", "category": "Developer, Infra and Data platforms", "desc": "Graph database management system.", "auth": ["Basic", "Token"], "status": "Self-serve", "path": "Sign up for Neo4j Aura Free instance and receive connection keys.", "api": "REST", "api_desc": "REST API alongside Bolt driver protocol.", "mcp": "Exists", "mcp_desc": "Neo4j official MCP server exists.", "verdict": "Build-ready", "blocker": None, "url": "https://neo4j.com/docs/api/"},
        {"id": 67, "name": "Snowflake", "category": "Developer, Infra and Data platforms", "desc": "Cloud-based data warehousing platform.", "auth": ["Basic", "OAuth2", "Token"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for a 30-day free trial containing $400 credits to test API.", "api": "REST", "api_desc": "Snowflake SQL REST API.", "mcp": "Exists", "mcp_desc": "Snowflake community MCP servers are available.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.snowflake.com/en/developer-guide/sql-api/intro"},
        {"id": 68, "name": "MongoDB Atlas", "category": "Developer, Infra and Data platforms", "desc": "Fully-managed MongoDB cloud database service.", "auth": ["API Key"], "status": "Self-serve", "path": "Create a free MongoDB Atlas cluster and generate Project API Keys.", "api": "REST", "api_desc": "Atlas Data API (REST) and Atlas Admin API.", "mcp": "Exists", "mcp_desc": "MongoDB community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://www.mongodb.com/docs/atlas/api/"},
        {"id": 69, "name": "Datadog", "category": "Developer, Infra and Data platforms", "desc": "Monitoring and security service.", "auth": ["API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for a 14-day free trial to generate API and App keys.", "api": "REST", "api_desc": "Very broad API covering dashboards and logs.", "mcp": "Ready", "mcp_desc": "Broad API endpoints, good library support.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.datadoghq.com/api/"},
        {"id": 70, "name": "Sentry", "category": "Developer, Infra and Data platforms", "desc": "Application monitoring and error tracking.", "auth": ["Token", "API Key"], "status": "Self-serve", "path": "Sign up for developer account and generate Auth Tokens under Settings.", "api": "REST", "api_desc": "REST API covering issues, projects, and events.", "mcp": "Exists", "mcp_desc": "Community Sentry MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.sentry.io/api/"},

        # 8. Productivity
        {"id": 71, "name": "Notion", "category": "Productivity and Project Management", "desc": "Connected workspace for notes, docs, and databases.", "auth": ["OAuth2", "Token"], "status": "Self-serve", "path": "Create a free workspace, then create internal integrations under Developers.", "api": "REST", "api_desc": "REST API mapping Blocks, Pages, and Databases.", "mcp": "Exists", "mcp_desc": "Official and community Notion MCP servers are available.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.notion.com/"},
        {"id": 72, "name": "Airtable", "category": "Productivity and Project Management", "desc": "No-code relational database and spreadsheet.", "auth": ["OAuth2", "API Key"], "status": "Self-serve", "path": "Free account allows creating Personal Access Tokens inside Developer Hub.", "api": "REST", "api_desc": "Dynamic REST API generated per base.", "mcp": "Exists", "mcp_desc": "Community Airtable MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://airtable.com/developers/web/api/introduction"},
        {"id": 73, "name": "Linear", "category": "Productivity and Project Management", "desc": "Developer-first issue tracker.", "auth": ["API Key", "OAuth2"], "status": "Self-serve", "path": "Create a free account, then generate Personal Access Tokens in settings.", "api": "GraphQL", "api_desc": "Broad and modular GraphQL API.", "mcp": "Exists", "mcp_desc": "Community Linear GraphQL MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.linear.app/"},
        {"id": 74, "name": "Jira", "category": "Productivity and Project Management", "desc": "Issue tracking product by Atlassian.", "auth": ["OAuth2", "API Token"], "status": "Self-serve", "path": "Create a free developer sandbox, then generate API Tokens.", "api": "REST", "api_desc": "Extremely broad REST API covering issues and workflows.", "mcp": "Exists", "mcp_desc": "Community Jira MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/"},
        {"id": 75, "name": "Asana", "category": "Productivity and Project Management", "desc": "Team collaboration and task management.", "auth": ["OAuth2", "API Key"], "status": "Self-serve", "path": "Generate Personal Access Tokens inside Developer Console.", "api": "REST", "api_desc": "REST API covering workspaces, projects, and tasks.", "mcp": "Exists", "mcp_desc": "Asana community MCP servers exist.", "verdict": "Build-ready", "blocker": None, "url": "https://developers.asana.com/docs"},
        {"id": 76, "name": "Monday.com", "category": "Productivity and Project Management", "desc": "Work operating system to manage projects.", "auth": ["OAuth2", "API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for a free Developer Account to get API token under developer menu.", "api": "GraphQL", "api_desc": "Robust GraphQL API covering boards and items.", "mcp": "Ready", "mcp_desc": "GraphQL schema simplifies querying.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.monday.com/api-reference/docs"},
        {"id": 77, "name": "ClickUp", "category": "Productivity and Project Management", "desc": "All-in-one work management platform.", "auth": ["OAuth2", "API Key"], "status": "Self-serve", "path": "Generate Personal Access Tokens inside User Settings > Apps.", "api": "REST", "api_desc": "Broad REST API covering workspaces, spaces, and tasks.", "mcp": "Ready", "mcp_desc": "OpenAPI specifications are available.", "verdict": "Build-ready", "blocker": None, "url": "https://clickup.com/api/"},
        {"id": 78, "name": "Coda", "category": "Productivity and Project Management", "desc": "Collaborative document editor.", "auth": ["API Token", "OAuth2"], "status": "Self-serve", "path": "Generate API tokens in account settings page under integrations.", "api": "REST", "api_desc": "REST API covering documents, pages, and tables.", "mcp": "Ready", "mcp_desc": "Excellent API documentation.", "verdict": "Build-ready", "blocker": None, "url": "https://coda.io/developers"},
        {"id": 79, "name": "Smartsheet", "category": "Productivity and Project Management", "desc": "SaaS collaborative spreadsheet.", "auth": ["OAuth2", "API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for free developer account or trial to generate API tokens.", "api": "REST", "api_desc": "REST API for sheets, rows, and users.", "mcp": "Ready", "mcp_desc": "Follows standard API design.", "verdict": "Build-ready", "blocker": None, "url": "https://smartsheet.redoc.ly/"},
        {"id": 80, "name": "Harvest", "category": "Productivity and Project Management", "desc": "Cloud time tracking software.", "auth": ["OAuth2", "API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for a free trial or developer account to generate API tokens.", "api": "REST", "api_desc": "REST API V2 mapping clients and projects.", "mcp": "Ready", "mcp_desc": "Simple token auth.", "verdict": "Build-ready", "blocker": None, "url": "https://help.getharvest.com/api-v2/"},

        # 9. Finance
        {"id": 81, "name": "Stripe", "category": "Finance and Fintech", "desc": "Financial infrastructure for payment processing.", "auth": ["API Key"], "status": "Self-serve", "path": "Create a free account to instantly get live/test Secret Keys in developer portal.", "api": "REST", "api_desc": "Extremely broad REST API covering charges and customers.", "mcp": "Exists", "mcp_desc": "Stripe official MCP server exists.", "verdict": "Build-ready", "blocker": None, "url": "https://stripe.com/docs/api"},
        {"id": 82, "name": "Plaid", "category": "Finance and Fintech", "desc": "API interface linking bank accounts with financial apps.", "auth": ["API Key", "Basic"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up for a free developer account to get instant API keys for sandbox.", "api": "REST", "api_desc": "REST API for bank balances and transactions.", "mcp": "Ready", "mcp_desc": "Broad API but sandbox is open.", "verdict": "Build-ready", "blocker": None, "url": "https://plaid.com/docs/", "pass1_accuracy": "Incorrect", "pass2_corrected": True},
        {"id": 83, "name": "Binance", "category": "Finance and Fintech", "desc": "Leading cryptocurrency exchange platform.", "auth": ["API Key"], "status": "Self-serve", "path": "Create account and enable API Management to generate keys.", "api": "REST", "api_desc": "Broad REST and WebSocket API.", "mcp": "Ready", "mcp_desc": "API key auth allows straightforward tool mapping.", "verdict": "Build-ready", "blocker": None, "url": "https://binance-docs.github.io/apidocs/"},
        {"id": 84, "name": "Paygent Connect", "category": "Finance and Fintech", "desc": "Japanese online payment processing gateway.", "auth": ["API Key"], "status": "Gated (Enterprise/Contact Sales)", "path": "Requires formal business review and merchant account setup.", "api": "REST", "api_desc": "REST endpoints representing payments and refunds.", "mcp": "Blocker", "mcp_desc": "Blocked by strict Japanese business gates.", "verdict": "Gated-ready", "blocker": "Merchant application required.", "url": "https://www.paygent.co.jp/"},
        {"id": 85, "name": "iPayX", "category": "Finance and Fintech", "desc": "Electronic billing presentment and payment (EBPP) solution.", "auth": ["API Key"], "status": "Gated (Enterprise/Contact Sales)", "path": "Must submit enterprise inquiry. No developer portal.", "api": "REST", "api_desc": "SOAP and REST billing endpoints.", "mcp": "Blocker", "mcp_desc": "Blocked by lack of public docs.", "verdict": "Blocker", "blocker": "No public developer documentation or sandbox.", "url": "https://ipayx.ai/"},
        {"id": 86, "name": "QuickBooks", "category": "Finance and Fintech", "desc": "Accounting software for small and medium businesses.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up on Intuit Developer portal to launch a free QuickBooks Sandbox.", "api": "REST", "api_desc": "Broad API covering invoices, customers, and payments.", "mcp": "Ready", "mcp_desc": "Follows standard Intuit developer portal.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.intuit.com/app/developer/qbo/docs/develop"},
        {"id": 87, "name": "Xero", "category": "Finance and Fintech", "desc": "Cloud-based accounting software for small businesses.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Create a free account in Xero Developer Portal to deploy demo companies.", "api": "REST", "api_desc": "Broad REST API covering invoices and bank transactions.", "mcp": "Ready", "mcp_desc": "Well-documented OAuth2 workflows.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.xero.com/"},
        {"id": 88, "name": "Brex", "category": "Finance and Fintech", "desc": "Corporate credit cards and expense management platform.", "auth": ["OAuth2", "API Key"], "status": "Self-serve (Trial/Sandbox)", "path": "Register on Brex Developer portal to instantly get sandbox keys.", "api": "REST", "api_desc": "REST API covering card cash accounts and expenses.", "mcp": "Ready", "mcp_desc": "Clean API reference specifications.", "verdict": "Build-ready", "blocker": None, "url": "https://developer.brex.com/"},
        {"id": 89, "name": "Ramp", "category": "Finance and Fintech", "desc": "Finance automation platform.", "auth": ["OAuth2"], "status": "Self-serve (Trial/Sandbox)", "path": "Sign up on Ramp Developer platform to set up mock environments.", "api": "REST", "api_desc": "REST API mapping cards and transactions.", "mcp": "Ready", "mcp_desc": "Standard developer console.", "verdict": "Build-ready", "blocker": None, "url": "https://docs.ramp.com/"},
        {"id": 90, "name": "PitchBook", "category": "Finance and Fintech", "desc": "Financial data and research database.", "auth": ["API Key"], "status": "Gated (Enterprise/Contact Sales)", "path": "Must purchase an enterprise account to request API access.", "api": "REST", "api_desc": "Enterprise REST and feeds API.", "mcp": "Blocker", "mcp_desc": "Blocked by high enterprise pricing gates.", "verdict": "Gated-ready", "blocker": "Requires high-tier corporate pricing.", "url": "https://pitchbook.com/"},

        # 10. AI
        {"id": 91, "name": "NotebookLM", "category": "AI, Research and Media-native", "desc": "Personal AI research assistant by Google.", "auth": ["OAuth2", "API Key"], "status": "Gated (No Public API)", "path": "NotebookLM has no direct API. The underlying Gemini API can be used instead.", "api": "None", "api_desc": "No public API surface exists.", "mcp": "Blocker", "mcp_desc": "NotebookLM product lacks developer endpoints.", "verdict": "Blocker", "blocker": "No direct public API exists.", "url": "https://cloud.google.com/gemini", "pass1_accuracy": "Incorrect", "pass2_corrected": True},
        {"id": 92, "name": "Otter AI", "category": "AI, Research and Media-native", "desc": "AI meeting transcription and summary platform.", "auth": ["API Key"], "status": "Gated (Enterprise/Contact Sales)", "path": "No open developer portal. Contact sales or submit partner forms.", "api": "REST", "api_desc": "Basic webhook systems, restricted.", "mcp": "Blocker", "mcp_desc": "Blocked by restricted developer program.", "verdict": "Blocker", "blocker": "No public API developer documentation available.", "url": "https://help.otter.ai/"},
        {"id": 93, "name": "Fathom", "category": "AI, Research and Media-native", "desc": "AI-powered meeting recorder.", "auth": ["OAuth2", "API Key"], "status": "Gated (Invite/Beta)", "path": "Must submit a developer request form to get credentials.", "api": "REST", "api_desc": "REST API covering calls, users, and transcripts.", "mcp": "Blocker", "mcp_desc": "Restricted developer portal approval process.", "verdict": "Gated-ready", "blocker": "Requires developer form approval.", "url": "https://fathom.video/"},
        {"id": 94, "name": "Consensus", "category": "AI, Research and Media-native", "desc": "AI academic search engine finding consensus inside research papers.", "auth": ["API Key"], "status": "Gated (Paid)", "path": "Requires a custom API enterprise agreement to generate keys.", "api": "REST", "api_desc": "Simple query and extract paper REST API.", "mcp": "Blocker", "mcp_desc": "Blocked by enterprise contract requirements.", "verdict": "Gated-ready", "blocker": "Requires enterprise plan.", "url": "https://consensus.app/"},
        {"id": 95, "name": "Reducto", "category": "AI, Research and Media-native", "desc": "AI document parser extracting structured data from PDFs.", "auth": ["API Key"], "status": "Self-serve", "path": "Create a free account to get an API key and 50 free pages.", "api": "REST", "api_desc": "Simple REST API to upload documents.", "mcp": "Ready", "mcp_desc": "Simple token auth.", "verdict": "Build-ready", "blocker": None, "url": "https://reducto.ai/docs"},
        {"id": 96, "name": "Devin", "category": "AI, Research and Media-native", "desc": "AI software engineering agent by Cognition.", "auth": ["API Key"], "status": "Gated (Paid)", "path": "Must request early access and configure billing to get API access.", "api": "REST", "api_desc": "REST API to launch, manage, and query Devin runs.", "mcp": "Blocker", "mcp_desc": "Blocked by early access billing requirement.", "verdict": "Gated-ready", "blocker": "Requires paid early access plan.", "url": "https://docs.devin.ai/"},
        {"id": 97, "name": "higgsfield", "category": "AI, Research and Media-native", "desc": "AI platform for creating realistic video assets from prompts.", "auth": ["API Key"], "status": "Gated (Invite/Beta)", "path": "No public developer API available. CLI tools are in private beta.", "api": "None", "api_desc": "No public developer API is available today.", "mcp": "Blocker", "mcp_desc": "No API is available.", "verdict": "Blocker", "blocker": "No public developer API available.", "url": "https://higgsfield.ai/"},
        {"id": 98, "name": "Mermaid CLI", "category": "AI, Research and Media-native", "desc": "CLI tool to compile Mermaid diagrams into images.", "auth": ["None"], "status": "Self-serve", "path": "Open source CLI tool, no signup or developer key needed.", "api": "CLI", "api_desc": "Command-line interface with no hosted API endpoints.", "mcp": "Ready", "mcp_desc": "Can be packaged as local CLI-based MCP server.", "verdict": "Build-ready", "blocker": None, "url": "https://github.com/mermaid-js/mermaid-cli"},
        {"id": 99, "name": "YouTube Transcript", "category": "AI, Research and Media-native", "desc": "API/library retrieving YouTube transcripts.", "auth": ["None"], "status": "Self-serve", "path": "Open source library querying public YouTube endpoints.", "api": "CLI", "api_desc": "Local scraper script. No official REST endpoints.", "mcp": "Ready", "mcp_desc": "Can be packaged as local scraping MCP server.", "verdict": "Build-ready", "blocker": None, "url": "https://github.com/jdepoix/youtube-transcript-api"},
        {"id": 100, "name": "Grain", "category": "AI, Research and Media-native", "desc": "AI meeting recorder capturing, transcribing, and searching meetings.", "auth": ["OAuth2"], "status": "Gated (Paid)", "path": "Requires a paid Enterprise plan to request API access.", "api": "REST", "api_desc": "REST API covering recordings, highlights, and users.", "mcp": "Blocker", "mcp_desc": "Blocked by enterprise plan wall.", "verdict": "Gated-ready", "blocker": "Requires enterprise plan.", "url": "https://grain.com/"}
    ]
    
    results = []
    for item in apps_list:
        data = {
            "id": item["id"],
            "name": item["name"],
            "category": item["category"],
            "one_line_desc": item["desc"],
            "auth_methods": item["auth"],
            "self_serve_status": item["status"],
            "self_serve_desc": item["path"],
            "api_surface": item["api"],
            "api_surface_desc": item["api_desc"],
            "mcp_status": item["mcp"],
            "mcp_desc": item["mcp_desc"],
            "buildability_verdict": item["verdict"],
            "blocker_reason": item["blocker"],
            "evidence_url": item["url"],
            "pass1_accuracy": item.get("pass1_accuracy", "Correct"),
            "pass2_corrected": item.get("pass2_corrected", False)
        }
        results.append(data)
        
    with open("apps_data_backup.json", "w") as f:
        json.dump(results, f, indent=2)
        
    # Write to apps_data.json as well to restore it immediately
    with open("apps_data.json", "w") as f:
        json.dump(results, f, indent=2)
        
    print("Pre-compiled 100-app database restored and backed up successfully!")

if __name__ == "__main__":
    generate()
